=== Shubhambawner/learner/Dev/IWT/xml2/books.dtd
<!ELEMENT BOOKS (book)> 

<!ELEMENT books (book*)> 
<!ELEMENT book (title,author,isbn,publisher,edition,price)> 
<!ELEMENT title (#PCDATA)> 
<!ELEMENT author (#PCDATA)> 
<!ELEMENT isbn (#PCDATA)> 
<!ELEMENT publisher (#PCDATA)> 
<!ELEMENT edition (#PCDATA)> 
<!ELEMENT price (#PCDATA)>

=== Shubhambawner/learner/Dev/IWT/xml2/Books1.xml
<!DOCTYPE books SYSTEM "./books.dtd">
<books>
    <book>
        <title>java server page</title>
        <author>hans bergsten</author>
        <isbn>81-265</isbn>
        <publisher>O'relilly</publisher>
        <edition>second</edition>
        <price>200</price>
    </book>
    <book>
        <title>c</title>
        <author>balaguruswamy</author>
        <isbn>81-695</isbn>
        <publisher>tata</publisher>
        <edition>second</edition>
        <price>400</price>
    </book>
    <book>
        <title>web program</title>
        <author>chirs bates</author>
        <isbn>81-265</isbn>
        <publisher>wiley</publisher>
        <edition>second</edition>
        <price>300</price>
    </book>
</books>
